# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gemmacpp <- function(args, prompt, verbosity = 1L) {
    .Call(`_rgemmacpp_gemmacpp`, args, prompt, verbosity)
}

test <- function(tokenizer, compressed_weights, model) {
    invisible(.Call(`_rgemmacpp_test`, tokenizer, compressed_weights, model))
}

